## カテゴリ毎の画像を predict_proba で一括処理してみる

In [20]:
import os
import datetime
import glob
import pandas as pd
import numpy as np
from PIL import Image

from tensorflow.keras.models import load_model

In [3]:
img_cat_paths = glob.glob('../../data/images/categorized-2/*')
print(img_cat_paths)

['../../data/images/categorized-2/0', '../../data/images/categorized-2/120', '../../data/images/categorized-2/1', '../../data/images/categorized-2/4', '../../data/images/categorized-2/3', '../../data/images/categorized-2/2']


In [4]:
img_paths = glob.glob(os.path.join(img_cat_paths[0], '*'))
print(img_paths[:10])

['../../data/images/categorized-2/0/3510_51hrOxCUAPL.jpg', '../../data/images/categorized-2/0/1586_61oaqjd8zjL.jpg', '../../data/images/categorized-2/0/1186_51W3vU8PLTL.jpg', '../../data/images/categorized-2/0/3671_511tzUSH1pL.jpg', '../../data/images/categorized-2/0/3317_514BfQwGaOL.jpg', '../../data/images/categorized-2/0/1189_61qaJjhikHL.jpg', '../../data/images/categorized-2/0/1687_61Aga5lQVzL.jpg', '../../data/images/categorized-2/0/2854_51dI5XisLEL.jpg', '../../data/images/categorized-2/0/3937_5182erE9KLL.jpg', '../../data/images/categorized-2/0/2349_61tkmhp+0LL.jpg']


In [5]:
img = Image.open(img_paths[0])
img_resize = img.resize((229, 229))
img_np = np.asarray(img_resize) / 255.0
x = img_np.reshape(1, 229, 229, 3)
print(x.shape)

(1, 229, 229, 3)


In [6]:
model = load_model('../../data/category-2.h5', compile=False)

In [9]:
np.set_printoptions(precision=5, suppress=True)

In [10]:
print(datetime.datetime.now().isoformat(), 'Start')

y = np.argmax(model.predict(x))
y_proba = model.predict_proba(x)
#y_proba = np.round((y_proba[0] * 100), 5)
print(y, y_proba)

print(datetime.datetime.now().isoformat(), 'End')

2020-06-20T13:34:08.285274 Start
2 [[0.00899 0.00001 0.99081 0.0002 ]]
2020-06-20T13:34:08.499627 End


In [22]:
book = []
x = []

for img_path in img_paths[:5]:
    img = Image.open(img_path)
    img_resize = img.resize((229, 229))
    img_np = np.asarray(img_resize) / 255.0

    x.append(img_np)
    book.append(os.path.basename(img_path).split('_')[0])

x = np.array(x)
print(x.shape)
print(book)

(5, 229, 229, 3)
['3510', '1586', '1186', '3671', '3317']


In [21]:
print(datetime.datetime.now().isoformat(), 'Start')

y = model.predict(x)
#y_proba = model.predict_proba(x)
#y_proba = np.round((y_proba[0] * 100), 5)
print(y)
#print(y_proba)

print(datetime.datetime.now().isoformat(), 'End')

2020-06-20T13:52:02.811140 Start
[[0.00899 0.00001 0.99081 0.0002 ]
 [0.00182 0.00163 0.97249 0.02406]
 [1.      0.      0.      0.     ]
 [0.99991 0.00001 0.00006 0.00002]
 [0.00239 0.0305  0.82374 0.14337]]
2020-06-20T13:52:03.207702 End
